apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  annotations:
    tailscale.com/expose: "true"
spec:
  type: NodePort
  selector:
    app: fastapi
  ports:
    - name: http
      port: 80   
      targetPort: 80
      nodePort: 31000